url: "https://www.gosiaradzyminska.pl"
title: gosiaradzyminska.pl
title_separator: "&#124;"
subtitle: ""
name: "Gosia Radzymińska"
description: "Gosia Radzymińska - Fizjoterapeutka Uroginekologiczna Kraków"
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num"
kramdown:
  syntax_highlighter: rouge
author_profile: true
author:
  name     : "Gosia Radzymińska"
  avatar   : "/images/miednica.jpg"
  bio      : "Certyfikowana fizjoterapeutka uroginekologiczna"
  location : "Kraków, Poland"
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope"
      url: "mailto:gosia.radzyminska@gmail.com"
    - label: 501288448
      icon: "fas fa-phone"
      url: "tel:+48501288448"
    - label: Instagram
      icon: "fab fa-fw fa-instagram-square"
      url: "https://www.instagram.com/gosiamamafizjo/"
    - label: ZnanyLekarz
      icon: "fa-znanylekarz"
      url: "https://www.znanylekarz.pl/malgorzata-radzyminska"
    - label: Booksy
      icon: "fa-booksy"
      url: "https://booksy.com/pl-pl/168253_holiestetyka_fizjoterapia_8820_krakow/staffer/570659#ba_s=Undefined"
footer:
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope"
      url: "mailto:gosia.radzyminska@gmail.com"
    - label: 501288448
      icon: "fas fa-phone"
      url: "tel:+48501288448"
    - label: Instagram
      icon: "fab fa-fw fa-instagram-square"
      url: "https://www.instagram.com/gosiamamafizjo/"
    - label: ZnanyLekarz
      icon: "fa-znanylekarz"
      url: "https://www.znanylekarz.pl/malgorzata-radzyminska"
    - label: Booksy
      icon: "fa-booksy"
      url: "https://booksy.com/pl-pl/168253_holiestetyka_fizjoterapia_8820_krakow/staffer/570659#ba_s=Undefined"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
google_analytics: "G-58QEKJP1F1"
